# Numpy

In [ ]:
# Importer le package numpy
import numpy as np

In [ ]:
# La documentation de numpy
help(np)

In [ ]:
# Créer un vecteur de taille 3
vector = np.array([9,8,4])
print(f"Le vecteur est:\n{vector}\nLa taille du vecteur est:\n{vector.shape}")

Le vecteur est:
[9 8 4]
La taille du vecteur est:
(3,)


In [ ]:
# Créer une matrice de dimension (2,3)
matrix = np.array([[2,4,5], [1,2,0]])
print(f"La matrice est :\n{matrix}\nLa dimension du vecteur est:\n{matrix.shape}")

La matrice est :
[[2 4 5]
 [1 2 0]]
La dimension du vecteur est:
(2, 3)


In [ ]:
# Créer une matrice de dimension (2,3) initialisée à 0
matrix = np.zeros((2,3))
print(f"La matrice est :\n{matrix}\nLa dimension du vecteur est:\n{matrix.shape}")

La matrice est :
[[0. 0. 0.]
 [0. 0. 0.]]
La dimension du vecteur est:
(2, 3)


In [ ]:
# Créer une matrice de dimension (2,3) initialisée à 1
matrix = np.ones((2,3))
print(f"La matrice est :\n{matrix}\nLa dimension du vecteur est:\n{matrix.shape}")

La matrice est :
[[1. 1. 1.]
 [1. 1. 1.]]
La dimension du vecteur est:
(2, 3)


In [ ]:
# Créer une matrice de dimension (2,3) initialisée à 9
matrix = np.full((2,3), 9)
print(f"La matrice est :\n{matrix}\nLa dimension du vecteur est:\n{matrix.shape}")

La matrice est :
[[9 9 9]
 [9 9 9]]
La dimension du vecteur est:
(2, 3)


In [ ]:
# Générer un vecteur aléatoire de taille dont les élément sont compris entre 1 et 5
vector = np.linspace(1,5,10)
print(f"Le vecteur est:\n{vector}\nLa taille du vecteur est:\n{vector.shape}")

Le vecteur est:
[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]
La taille du vecteur est:
(10,)


In [ ]:
# Créer une matrice aléatoire suivant une distribution uniforme de dimension (5,4)
matrix = np.random.rand(5,4)
print(f"La matrice est :\n{matrix}\nLa dimension du vecteur est:\n{matrix.shape}")

La matrice est :
[[0.12332786 0.10217774 0.65848381 0.1236371 ]
 [0.2295589  0.14673095 0.92125357 0.92516779]
 [0.9127768  0.05371393 0.33502013 0.771212  ]
 [0.40344172 0.25628726 0.01613367 0.0350469 ]
 [0.84303532 0.12630107 0.37086446 0.57431517]]
La dimension du vecteur est:
(5, 4)


In [ ]:
# Créer une matrice aléatoire suivant une distribution normale de dimension (5,4)
matrix = np.random.randn(5,4)
print(f"La matrice est :\n{matrix}\nLa dimension du vecteur est:\n{matrix.shape}")

La matrice est :
[[ 0.69219421 -0.64106179  0.80961834 -0.57778373]
 [-0.30861969  1.47849239 -1.77586103  0.09000056]
 [-1.2388066  -0.96556868  0.81824781  1.67370366]
 [-0.47265541 -0.18851269 -0.07883512  1.38988871]
 [ 0.166392    0.07536031  0.9868846  -1.92928392]]
La dimension du vecteur est:
(5, 4)


**Pairwise multiplication**

In [ ]:
# MULTIPLICATION ENTRE VECTEURs
# La multiplication entre vecteurs est possiblie que si les vecteurs sont de même taille.
# La sortie est un vecteur de même taille que les deux vecteurs

vector1 = np.random.randn(5)
vector2 = np.random.rand(5)

pairwise = vector1*vector2
print(f"Le vecteur de sortie est:\n{pairwise}\nLa taille du vecteur est:\n{pairwise.shape}")

Le vecteur de sortie est:
[ 0.01607465 -0.28206204  0.64671521 -0.87554336 -0.80629549]
La taille du vecteur est:
(5,)


In [ ]:
# MULTIPLICATION ENTRE MATRICES
# La multiplication entre matrices est possiblie que si les matrices sont de même taille.
# La sortie est une matrice de même taille que les deux matrices

vector1 = np.random.randn(5, 2)
vector2 = np.random.rand(5, 2)

pairwise = vector1*vector2
print(f"La matrice de sortie est:\n{pairwise}\nLa taille de la matrice est:\n{pairwise.shape}")

La matrice de sortie est:
[[-0.43845231 -0.21752073]
 [ 0.37735281  0.12301385]
 [ 0.18328045  0.64514771]
 [-0.53149465  0.14952345]
 [-0.58474633 -0.56538565]]
La taille de la matrice est:
(5, 2)


In [ ]:
# MULTIPLICATION ENTRE VECTEUR ET MATRICE
# La multiplication entre VECTEUR ET MATRICE est possiblie que si le nombre de colonnes de la matrice est égal à la taille du vecteur
# La sortie est une matrice de même taille que la matrice

vector1 = np.random.randn(5, 2)
vector2 = np.random.rand(2)

pairwise1 = vector1*vector2
pairwise2 = vector2*vector1
print("1 ER CAS:")
print(f"La matrice de sortie est:\n{pairwise1}\nLa taille de la matrice est:\n{pairwise1.shape}")
print()
print("2 ÈME CAS:")
print(f"La matrice de sortie est:\n{pairwise2}\nLa taille de la matrice est:\n{pairwise2.shape}")

1 ER CAS:
La matrice de sortie est:
[[-1.38905653  0.0702349 ]
 [ 0.03813999  0.05295878]
 [ 1.82340946 -0.13640185]
 [ 0.33236966 -0.24771878]
 [-0.71260141  0.0798215 ]]
La taille de la matrice est:
(5, 2)

2 ÈME CAS:
La matrice de sortie est:
[[-1.38905653  0.0702349 ]
 [ 0.03813999  0.05295878]
 [ 1.82340946 -0.13640185]
 [ 0.33236966 -0.24771878]
 [-0.71260141  0.0798215 ]]
La taille de la matrice est:
(5, 2)


**Dot product**

In [ ]:
# Le DOT PRODUCT ENTRE VECTEURS
# Le dot product entre vecteurs est possiblie que si les vecteurs sont de même taille.
# La sortie est un scalaire

vector1 = np.random.randn(5)
vector2 = np.random.rand(5)

dot1 = vector1.dot(vector2)
dot2 = vector2.dot(vector1)

print("1 ER CAS")
print(f"Le scalaire de sortie est:\n{dot1}")

print("2 ÈME CAS")
print(f"Le scalaire de sortie est:\n{dot2}")

1 ER CAS
Le scalaire de sortie est:
1.0768735628019432
2 ÈME CAS
Le scalaire de sortie est:
1.0768735628019432


In [ ]:
# DOT PRODUCT ENTRE MATRICES
# Le Dot product entre A et B est possible que si le nombre de colonnes de A est égal au nombre de lignes de B
# La sortie est une matrice de dimension le nombre de colonnes de A et le nombre de colonnes de B

matrix1 = np.random.randn(5, 2)
matrix2 = np.random.rand(2, 5)

dot = matrix1.dot(matrix2)
print(f"La matrice de sortie est:\n{dot}\nLa taille de la matrice est:\n{dot.shape}")

La matrice de sortie est:
[[-0.26282919 -0.228402   -0.35022539 -0.20903043 -0.46832965]
 [ 0.00705422  0.01741155 -0.12267683  0.09598272 -0.22490056]
 [-0.46320242 -0.42696121 -0.33118542 -0.56411067 -0.31107562]
 [-1.07990686 -1.01100405 -0.58960636 -1.44004943 -0.39707897]
 [-0.55988156 -0.51462067 -0.41734981 -0.67019199 -0.40663995]]
La taille de la matrice est:
(5, 5)


In [ ]:
# DOT PRODUCT ENTRE VECTEURS ET MATRICES
# Le DOT product entre vecteurs et matrices est possible que si la taille du vecteur est égal au nombre de colonnes de la matrice
# La sortie est un vecteur de la taille le nombre de colonnes de la matrice

matrix = np.random.randn(5, 2)
vector = np.random.rand(5)

dot = vector.dot(matrix)
print(f"La matrice de sortie est:\n{dot}\nLa taille du vecteur est:\n{dot.shape}")

La matrice de sortie est:
[ 1.27246882 -0.50373729]
La taille du vecteur est:
(2,)


np.linalg

    Matrix and vector products
    --------------------------
    
       multi_dot
       matrix_power
    
    Decompositions
    --------------
    
       cholesky
       qr
       svd
    
    Matrix eigenvalues
    ------------------
    
       eig
       eigh
       eigvals
       eigvalsh
    
    Norms and other numbers
    -----------------------
    
       norm
       cond
       det
       matrix_rank
       slogdet
    
    Solving equations and inverting matrices
    ----------------------------------------
    
       solve
       tensorsolve
       lstsq
       inv
       pinv
       tensorinv