## Recalls

In [ ]:
# Example
import numpy as np

# 1. Vector Addition
def vector_addition(u, v):
    return np.add(u, v)

# 2. Vector Subtraction
def vector_subtraction(u, v):
    return np.subtract(u, v)

# 3. Scalar-Vector Multiplication
def scalar_vector_multiplication(scalar, v):
    return scalar * v

# 4. Matrix Addition
def matrix_addition(A, B):
    return np.add(A, B)

# 5. Matrix Subtraction
def matrix_subtraction(A, B):
    return np.subtract(A, B)

# 6. Scalar-Matrix Multiplication
def scalar_matrix_multiplication(scalar, A):
    return scalar * A

# 7. Transpose of a Matrix
def matrix_transpose(A):
    return A.T

# 8. Inverse of a Matrix
def matrix_inverse(A):
    return np.linalg.inv(A)

# 9. Determinant of a Matrix
def matrix_determinant(A):
    return np.linalg.det(A)

# 10. Eigenvalues and Eigenvectors of a Matrix
def matrix_eigen(A):
    eigenvalues, eigenvectors = np.linalg.eig(A)
    return eigenvalues, eigenvectors

# 11. Singular Value Decomposition (SVD) of a Matrix
def matrix_svd(A):
    U, S, V = np.linalg.svd(A)
    return U, S, V

##### Creation
Vectors and matrices in Python can be defined manually using Numpy arrays:

In [ ]:
# Define a vector
v = np.array([4, 6, -1])
print(v)

[ 4  6 -1]


In [ ]:
# Dimension
print(v.shape)

# Number of elements
print(v.size)

(3,)
3


In [ ]:
# Define a matrix
M = np.array([[1, 3, 7], [8, 4, 5]])
print(M)

[[1 3 7]
 [8 4 5]]


In [ ]:
# Dimension
print(M.shape)

(2, 3)


In [ ]:
# Number of elements
print(M.size)

6


In [ ]:
# Type of elements
M.dtype

dtype('int64')

The type can be changed a posteriori using ```asarray```:

In [ ]:
M = M.astype('int32')
M.dtype

dtype('int32')

The type can be set when creating the matrix:

In [ ]:
M = np.array([[1, 3, 7], [8, 4, 5]], dtype='int32')
M.dtype

dtype('int32')

##### Creation using numpy functions

In [ ]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Null matrix of shape (3,3)
Z = np.zeros((3,3))
print(Z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# A Matrix filled with 1
L = np.ones((2,3))
print(L)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# Identity matrix
I = np.eye(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# Diagonal matrix
D = np.diag([2, -1, 3])
print(D)

[[ 2  0  0]
 [ 0 -1  0]
 [ 0  0  3]]


##### Reshaping

In [ ]:
x = np.arange(1,10)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# Reshape
x.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# Reshape creates a new reshaped object
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Resize reshapes inplace
x.resize((3,3))
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# Reshapes to the initial dimension
x.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# ravel and flaten do not modify the array (not inplace)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### Concatenation

In [ ]:
M = np.array([[1, 2], [3, 4]])
print(M)

[[1 2]
 [3 4]]


In [ ]:
N = np.array([[5, 6], [7, 8]])
print(N)

[[5 6]
 [7 8]]


In [ ]:
# Concatenate M and N vertically
print(np.concatenate((M, N)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
# Concatenate M and N horizontally
print(np.concatenate((M, N), axis=1))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [ ]:
# Another way to concatenate vertically
print(np.vstack((M,N)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
# Another way to concatenate horizontally
print(np.hstack((M,N)))

[[1 2 5 6]
 [3 4 7 8]]


#### Inexing and slicing

One dimensional numpy arrays can be sliced exactly as a list (Check TP0 for details).

In [ ]:
M = np.array([[4,2,-2],[1,0,1],[6,-4,3]])
print(M)

[[ 4  2 -2]
 [ 1  0  1]
 [ 6 -4  3]]


In [ ]:
# Access to a specific items
print(M[0,0])
print(M[1,2])

4
1


In [ ]:
# Another way to access to items
print(M[0][0])
print(M[1][2])

4
1


In [ ]:
# Access to a specific line
print(M[0,:])

[ 4  2 -2]


In [ ]:
# Access to a specific column
print(M[:,0])

[4 1 6]


In [ ]:
# Access to a specific bloc
print(M[1:,1:])

array([[ 0,  1],
       [-4,  3]])

In [ ]:
# Logical mask
print(M < 2)

[[False False  True]
 [ True  True  True]
 [False  True False]]


#### Algebraic operations

In [ ]:
# Vectors definitions
x = np.array([1, 3])
y = np.array([4, 2])

# Matrices definitions
M = np.array([[1, -5], [-1, 4]])
N = np.array([[2, 1], [-4, 6]])

In [ ]:
# Vector addition
print(x+y)

[5 5]


In [ ]:
# Matrix addition
print(M+N)

[[ 3 -4]
 [-5 10]]


In [ ]:
# Another way to perform addition (true fro both vectors and matrices)
print(np.add(M,N))

[[ 3 -4]
 [-5 10]]


In [ ]:
# Subtraction
print(M-N)

[[-1 -6]
 [ 3 -2]]


In [ ]:
# Another way to perform substraction
print(np.subtract(M,N))

[[-1 -6]
 [ 3 -2]]


In [ ]:
# Element wise product
print(M*N)

[[ 2 -5]
 [ 4 24]]


In [ ]:
# Power (element wise power)
print(M**2)

[[ 1 25]
 [ 1 16]]


In [ ]:
# Dot product
x.dot(y)

10

In [ ]:
# Matrix product
print(M @ N)

[[ 22 -29]
 [-18  23]]


In [ ]:
# Another way to perform matrix product
print(M.dot(N))

[[ 22 -29]
 [-18  23]]


In [ ]:
# Matrix vector product
print(M @ x)

[-14  11]


In [ ]:
# Another way to perform matrix vector product
print(M.dot(x))

[-14  11]


## Exercices

### Exercice 1

1. Create a matrix A and B of shape (5, 10), and a vector C of size 10, using the randn function from numpy.

In [ ]:
# Answer

2. Compute the sum D and the subtraction F of matrices A and B. What is the shape of the obtained matrices?

In [ ]:
# Answer

3. Compute the product of λ=10 and the vector C. What is the dimension of λC?

In [ ]:
# Answer

4. Calculate the sum and the element-wise multiplication between C and F. What is the dimension of the outputs?

In [ ]:
# Answer

5. Calculate G, the dot product between C and F, and give the dimension of G. What is the difference between dot product and multiplication of vectors?

In [ ]:
# Answer

6. Calculate the sum and multiplication between F and B. Give the dimension of each result.

In [ ]:
# Answer

7. Calculate the dot product between B and F (in this order). Give the dimension of the result.

In [ ]:
# Answer

8. Calculate the dot product between F and B (in this order). If it works, give the dimension of the result; else propose a solution, and give the dimension of the result.

In [ ]:
# Answer

9. Calculate I the dot product between A and B. Give the dimension of I.

In [ ]:
# Answer

10. Give the detiminant of I.

In [ ]:
# Answer

11. Give J the Inverse of I, if I is inversible.

In [ ]:
# Answer

12. Decompose the matrix I using eigendecomposition method.

In [ ]:
# Answer

13. Decompose the matrix I using svd method

In [ ]:
# Answer

### Exercice 2: Power iteration method

The objective of this excercice is to compute the eigenvector of a matrix associated to its largest eigenvector using the power iteration method: Given a squared matrix $A$ of shape $n\times n$ and a vector $x_0\in\mathbb{R}^n$, then the sequence of vectors $(x_k)_{k\in\mathbb{N}}$ defined as:
$$
x_{k+1}=\frac{Ax_k}{\Vert A x_k\Vert},
$$
converges to the largest eigenvector in absolute value (we admit this result).
  

1. Define a function ```power_iteration(A, x0, k)``` that returns $x_k$.



In [ ]:
# Answer


2. Using the function ```power_iteration```, compute the largest eigenvector of the matrix
$$
A = \begin{bmatrix} 0.5 & 0.5\\ 0.2 & 0.8 \end{bmatrix}
$$

In [ ]:
# Answer


3. Compute the eigen value associated to this vector.
***Indication:*** If $v$ is a normalized eigenvector of $A$, then its associated eigenvalue is given by $λ=Av⋅v$

In [ ]:
# Answer


4. Adapt the function ```power_iteration``` such that it allows to compute the largest eigenvalue with its associated eigenvector of a matrix given precision value.

In [ ]:
# Answer


5. Compare the execution times of the previous script and the numpy function for matrices of shape $n\times n$ with $n\in \{10, 100, 1000\}$   

In [ ]:
# Answer


### Exercice 3

Let $A$ be a matrix and $b$ a vector defined by:

```
M = np.random.randn(3, 3)
A = M + M.T
b = np.random.rand(3)
```



Solve the linear system $Ax=b$ with two different methods

### Exercise 4


Write a Python program that performs the following tasks:

1. Generate a random vector in 3D space.<br>
2. Choose a target subspace by specifying a basis (orthonormal vectors) for the subspace.<br>
3. Project the random vector onto the target subspace to find its orthogonal projection.<br>
4. Calculate the residual vector as the difference between the original vector and its projection.<br>
5. Verify that the projection and residual vectors are orthogonal.

### Exercice 4: Orthogonal Projections



The objectif of the exercice is to compute the orthogonal projection of a vector into a given subspace. We let be $x\in \mathbb{R}^{n}$, $E\subset\mathbb{R}^{n}$ a subspace of dimension $p$, and $B=\{e_1, ⋯,e_{p} \}$ an orthonormal basis of $E$. Then, the orthogonal projection of the vector $x$ on $E$ is given by
$$
p_E(x) = \sum_{i=1}^{p} <x,e_i>e_i
$$

In a more general case, given the matrix $A$ the projection matrix is given by
$$
P = A(A^tA)^{-1}A^t
$$
The projection matrix verifies the following properties:


1.   $P$ is a squared matrix.
2.   Symmetry $P^t=P$.
3.   $P$ is idempotent: $P^2= P$.


1. Define a function ```is_orthonormal(A)``` that takes as parameters the matrix $A$ of wich the columns corresponds to the basis vectors of the target subspace and returns  ```True``` if the basis is orthonormal ```False``` otherwise.

In [ ]:
# Answer


2. Define a function ```project(B,x)``` that takes as parameters a vector $x\in \mathbb{R}^{n}$ and ```B``` a list of vectors of the basis $B$.

In [ ]:
# Answer


3. Let $E$ the subspace spanned by the basis $B = \left\{\left(\frac{1}{\sqrt{2}},\frac{1}{\sqrt{2}},0\right)^t,\left(\frac{1}{\sqrt{3}},-\frac{1}{\sqrt{3}},\frac{1}{\sqrt{3}}\right)^t\right\}$. Verify that the basis is orthonormal.

In [ ]:
# Answer


4. Generate a three dimensional vector (i.e., n=3). And compute its projection on $E$.  

In [ ]:
# Answer


5. Let be $E$ the subspace spanned by $B=\left\{ (0,1,1)^t,(1,-1,1)^t \right\}$, and $x=(1,2,-1)^t$. Compute the projection matrix $P$ and verify numerically that it satisfies the three properties listed above.

In [ ]:
# Answer


6. Compute the projection of $x$ on $E$.

In [ ]:
# Answer


### Exercise 5: Diagonalization of symmetric Matrices


The objective of this exercice is to omplement a Python program that demonstrates the diagonalization of a symmetric matrix:

1. Generate a random symmetric matrix of a specified size.<br>



In [ ]:
# Answer


2. Compute the eigenvalues and eigenvectors of the symmetric matrix.

In [ ]:
# Answer


3. Verify that the eigenvectors are orthogonal.

In [ ]:
# Answer


4. Construct a diagonal matrix using the eigenvalues.

In [ ]:
# Answer


5. Reconstruct the original matrix using eigenvectors and the diagonal matrix.

In [ ]:
# Answer


### Exercise 6:
1. Define a class Squared_matrix that inherits from the class ```np.matrix``` with the attribute values which corresponds to the squared matrix, and a constructor that instanciates the classe (it should return an error message if the matrix is not squared) and an ```__str()__``` that prints the matrix.

In [ ]:
# Answer


2. Define a method:
* ```rank()``` that returns the rank of the matrix.  
* ```is_invertible```that returns a boolean (```True``` if the matrix is invertible ```False``` otherwise).
* ```inverse()``` that returns the inverse of the matrix when possible.
* ```eigenvalues()``` and ```eigenvectors``` that return the eigenvalues and eigenvectors of the matrix.

In [ ]:
# Answer


3. Given a squared matrix $A$, we recall the definition of some norms:

$$
\begin{align*}
&||A||_F \, = \sqrt{\sum_{i=1}^n\sum_{j=1}^n a^2_{i,j}} = \sqrt{tr(A^tA)},  \\
&||A||_1 \,\, = \max_{1\leq j\leq n} \sum_{i=1}^{n}|a_{i,j}|, \\
&||A||_2 \,\, = \sqrt{\rho(A^tA)}, \\
&||A||_\infty = \max_{1\leq i\leq n} \sum_{j=1}^{n}|a_{i,j}|,
\end{align*}
$$
where $\rho(\cdot)$ design the spectral radius, i.e., the largest (in absolute value) eigenvalue of a matrix. Define the method ```norm_f(ind)``` that returns the norm given the indice ```ind``` (the indice is a string with possible values: ```"F"```,```"1"```,```"2"```, and ```"inf"```).


In [ ]:
# Answer
