# Introduction into Mathematical Modelling

* Consider predicting person's **height** *from* its **age**:


* Mathematically, this task translates to:

\\

   \begin{equation}
      \mbox{height} = f(\mbox{age}),
   \end{equation}

\\

 where $f$ is logarithmic function with parameters

\\

   \begin{equation}
    f(\mbox{age}) = 2.2 \log \left(80 \times \mbox{age} \right). 
   \end{equation}

\\

 ![](https://drive.google.com/uc?export=view&id=1vBEmQ5NtQxUv1wcma2NiU7kvw2US2Y9n)

* In model 

\\

\begin{equation}
    f(\mbox{age}) = 2.2 \log \left(80 \times \mbox{age} \right)
\end{equation}

\\

* both input and output (age and height) are **single numbers**;


* In case where input and output are **vectors**, the model would have been expressed with ***matrices***;


* **Linear Algebra** is the branch of mathematics that study linear transformations between vectors in **linear** fashion;


* In Deep Leqrning, models are built over $4$ algebraic objects: 
    1. **scalars**;
    2. **vectors**;
    3. **matrices**;
    4. **tensors**.

# 1. Linear Algebra Prerequisites

## Scalars

* Scalars are single numbers  defined by the set to which they belong;

* For example, number of persons in the classroom is $p \in {\rm I\!N}$ while the temperature is $t \in {\rm I\!R}$;

* In Python, scalar are defined as

In [ ]:
n = 52
t = 12.5
print("we have " + str(n) + " students and the temperature is " + str(t) + " degrees.")

we have 52 students and the temperature is 12.5 degrees.


## Vectors

### Definition

* Vectors are ordered array of numbers and can represent all sort of data (image, video, text,...).

* Let $\bf{x}$ be a vector with $d$ elements

\begin{equation}
\bf{x} = 
\begin{bmatrix}
    x_1\\
    \vdots\\
    x_d\\
\end{bmatrix}.
\\
\end{equation}


* If $x_1,\ldots, x_d \in {\rm I\!R}$ then we write $\bf{x} \in {\rm I\!R}^d$;

* Addition and multiplication by scalers must always produce vectors;



* Let $\bf{x}$ and $\bf{y}$ be two vectors defined in ${\rm I\!R}^2$ such that  

\begin{equation}
\bf{x} = 
\begin{bmatrix}
    3\\
    1\\
\end{bmatrix},
\bf{y} = 
\begin{bmatrix}
    2\\
    3\\
\end{bmatrix}.
\end{equation}

* $\bf{x}$ and $\bf{y}$ are geometrically represented as follows

 ![](https://drive.google.com/uc?export=view&id=13ajZipJkZ8oTIDsT-4skOO661_5qfsds)

* Vectors are essentially characterized by:

  1. **Direction**; 

  2. **Length** obtained with Pythagorean theorem:

  \begin{equation}
  \vert\vert \bf{x}\vert\vert_2 = \sqrt(\sum_{i = 1}^{2} x_i^2).
  \end{equation}


* Vectors **are not points**:
  * Vectors are objects characterized by direction and length;
  * Points have no direction and their length is equal to zero;
 
* For readability reasons we tend to **represent** vectors as **points** but keep in mind these points are related to the origin and possess direction and length.

 ![](https://drive.google.com/uc?export=view&id=1Dn1fcTv1RRvHFH9TxDVsKlyoqEsSZqXL)
 

### Operations

#### **Transposition**

* Let $\bf{x} \in {\rm I\!R}^d$, **By default**, $\bf{x}$ is defined as **column** vector;

\begin{equation}
\bf{x} = 
\begin{bmatrix}
    x_1\\
    \vdots\\
    x_d\\
\end{bmatrix}.
\end{equation}


* Vectors can also be defined as ***row*** like 

\begin{equation}
\bf{y} = \left[ y_1,\ldots, y_d \right].
\\
\end{equation}

* Column and row versions of a same vector are not the same and relate through **transpose** operator;

* $\bf{x}$ transpose is written $\bf{x}^T$. **Column** vector can be written $\bf{x} = \left[ x_1,\ldots, x_d \right]^T$. 

#### **Scalar Multiplication**

* Let $\alpha \in {\rm I\!R}$ be a scalar and $\bf{x} \in {\rm I\!R}^m$, $\bf{x}$ can be ***scaled*** by $\alpha$ as follows

\begin{equation}
\alpha \bf{x} = 
\begin{bmatrix}
\alpha x_1\\
\vdots\\
\alpha x_m
\end{bmatrix}.
\end{equation}

* Let $\alpha = 2, \beta = -\frac{1}{2}$ be two scalars respectively applied on  $\bf{x}$, $\bf{y} \in {\rm I\!R}^2$   

\begin{equation}
\bf{x} = 
\begin{bmatrix}
    3\\
    1\\
\end{bmatrix}, \quad
\bf{y} = 
\begin{bmatrix}
    2\\
    3\\
\end{bmatrix}.
\end{equation}

* Scaled vectors are 

\begin{equation}
\alpha\bf{x} = 
\begin{bmatrix}
    6\\
    2\\
\end{bmatrix}, \quad
\beta \bf{y} = 
\begin{bmatrix}
    -1\\
    -\frac{3}{2}\\
\end{bmatrix}.
\end{equation}.

 ![](https://drive.google.com/uc?export=view&id=1SAEJfi3j5mtswhm7iRJ80UdvhuObR4wQ)


#### **Unit Vectors**

* Let $\bf{x} \in {\rm I\!R}^m$. The unit-vector of $\bf{x}$ is $\bf{u}$ defined as 

\begin{equation}
\bf{u} = \frac{1}{\vert\vert \bf{x} \vert\vert} \bf{x}.
\end{equation}

* $\bf{u}$ has same direction as $\bf{x}$ with $\vert\vert \bf{u} \vert\vert = 1$. 

#### **Addition**

* Let  $\bf{x}$ and $\bf{y} \in {\rm I\!R}^m$.

* Addition and subtraction between $\bf{x}$ and $\bf{y}$ are respectively defined as

\begin{equation}
 \bf{x} + \bf{y} = 
\begin{bmatrix}
 x_1 + y_1\\
\vdots\\
 x_m + y_m
\end{bmatrix},
 \bf{x} - \bf{y} = 
\begin{bmatrix}
 x_1 - y_1\\
\vdots\\
 x_m - y_m
\end{bmatrix}, 
\end{equation}

 ![](https://drive.google.com/uc?export=view&id=1L4mp3yfTIGh330zVotYH4Klbt5VnZPeG)

#### **Dot Product**

* Dot product between $\bf{x}$ and $\bf{y} \in {\rm I\!R}^m$ is  ***scalar*** defined as 

\begin{equation}
\bf{x}.\bf{y} = \vert\vert\bf{x}\vert\vert \times \vert\vert \bf{y}\vert\vert \times \cos(\theta),
\end{equation}

where $\theta$ is the angle between $\bf{x}$ and $\bf{y}$; 

* $\cos(\theta) \in [-1, 1]$ measures how much $\bf{x}$ and $\bf{y}$ are oriented in terms of direction;

* A more convenient way to compute dot-product is the algebraic formula

\begin{equation}
\bf{x}.\bf{y} = \sum_{i = 1}^{m} x_i y_i.
\end{equation}


#### **Illustration of Dot Product**


\begin{equation}
\bf{x}.\bf{y} = \vert\vert\bf{x}\vert\vert \times \vert\vert \bf{y}\vert\vert \times \cos(\theta).
\\
\end{equation}

* $\cos(\theta)$ measures similarity between $\bf{x}$ and $\bf{y}$ in terms of direction where:
  * $\cos(\theta) = 1$ means perfect alignement
  * whereas $\cos(\theta) = -1$ means perfect opposition. 


 
* Consider the following dot products:
 
  * $\bf{x},\bf{y}$ are perfectly aligned resulting into $\cos(\theta) = 1$;

  * $\bf{x},\bf{p}$ and $\bf{x},\bf{u}$ are perpendicular resulting into null dot products because of $\cos(\frac{\pi}{2}) = \cos(\frac{3\pi}{2}) = 0$;

  * $\bf{x},\bf{z}$ are aligned but look into opposite direction producing $\cos(\theta) = -1$;

  * vectors forming angle  $\theta \in \left] \frac{3\pi}{2},\frac{\pi}{2} \right[$ with $\bf{x}$ **tend** to the direction of $\bf{x}$;

  * inversely, vectors forming angle  $\theta \in \left] \frac{\pi}{2},\frac{3\pi}{2} \right[$ with $\bf{x}$ evolve in opposite direction to $\bf{x}$.

 ![](https://drive.google.com/uc?export=view&id=13LCU8vo1zUba4GpMyOSVsIu-cumnX-2w)

### Vectors in Python



In [ ]:
import numpy as np
x = np.array([3,1], dtype = np.float)
y = np.array([2,3], dtype = np.float)

ax = 2 * x 
print('scaled x by 2 = ')
print(ax)

a = x + y
print('\nx + y = ')
print(a)

s = x-y
print('\nx - y = ')
print(s)

x = np.array([3,1], dtype = np.float)
y = np.array([2,3], dtype = np.float)

d = x.dot(y)
print('\nthe dot product x.y = ' + str(d))

scaled x by 2 = 
[6. 2.]

x + y = 
[5. 4.]

x - y = 
[ 1. -2.]

the dot product x.y = 9.0


## Matrices

### Definition



* Visually, matrices tend to be defined as grid of numbers where elements are identified by row and column indices;

* Algebraically, matrices are functions that **linearly transform** one vector into another;

* Let $\bf{W}$ be matrix of $m$ rows and $d$ columns


\begin{equation}
\bf{W} =
\begin{bmatrix}
w_{11} & \ldots & w_{1d} \\
\vdots & \ddots & \vdots \\
w_{m1} & \ddots & w_{md}
\end{bmatrix}.
\\
\end{equation}


*  $\bf{W}$ transforms input vectors $\bf{x} \in \rm I\!R^d$ to output vectors $\bf{y} \in \rm I\!R^m$;



* Let $\bf{A}$ be a $2 \times 2$ matrix and  an input vector $\bf{x}$ where 

\begin{equation}
\bf{A} =
\begin{bmatrix}
-2 & 0\\
0 & -2
\end{bmatrix},
\quad \bf{x} = 
\begin{bmatrix}
    3\\
    1\\
\end{bmatrix}
\end{equation}

* We define $\bf{y}$ as the linear transformation of $\bf{x}$ through $\bf{A}$

\begin{equation}
\bf{y} = 
3 
\begin{bmatrix}
    -2\\
    0\\
\end{bmatrix}+1
\begin{bmatrix}
    0\\
    -2\\
\end{bmatrix}=
\begin{bmatrix}
-6\\
-2
\end{bmatrix}.
\end{equation}


### Operations

#### Transposition

* Let $\bf{A} \in \rm I\!R^m \times \rm I\!R^d$ or ($\rm I\!R^{m \times d}$) be matrix with $m$ rows and $d$ columns;

\begin{equation}
\bf{A} =
\begin{bmatrix}
a_{11} & \ldots & a_{1d} \\
\vdots & \ddots & \vdots \\
a_{m1} & \ddots & a_{md}
\end{bmatrix}.
\end{equation}

* Transposed $\bf{A}$ noted $\bf{A}^T$ is a matrix with $d$ rows and $m$ columns where each $j$-th column vector in $\bf{A}^T$ corresponds to the $j$-th row vector in $\bf{A}$;   

\begin{equation}
\bf{A}^T =
\begin{bmatrix}
a_{11} & \ldots & a_{m1} \\
\vdots & \ddots & \vdots \\
a_{1d} & \ddots & a_{md}
\end{bmatrix}.
\end{equation}

#### Scalar Matrix Multiplication

* Let $\alpha \in \rm I\!R$ and $\bf{A} \in \rm I\!R^m \times \rm I\!R^d$,  product $\alpha \bf{A}$ is defined as

\begin{equation}
\alpha \bf{A} =
\begin{bmatrix}
\alpha a_{11} & \ldots & \alpha a_{1d} \\
\vdots & \ddots & \vdots \\
\alpha a_{m1} & \ddots & \alpha a_{md}
\end{bmatrix}.
\end{equation}

* $\alpha \bf{A} = \bf{A} \alpha $ 

#### Vector Matrix Multiplication

* Let $\bf{x} \in \rm I\!R^d$ and $\bf{A} \in \rm I\!R^m \times \rm I\!R^d$,  as described above, $\bf{A} \bf{x} \$ is merely the sum

\begin{equation}
\bf{A} \bf{x} =
x_1
\begin{bmatrix}
a_{11}\\
\vdots\\
a_{m1}
\end{bmatrix}
+\cdots+
x_d
\begin{bmatrix}
a_{m1}\\
\vdots\\
a_{md}
\end{bmatrix}.
\end{equation}


* The weighted sum above is compactly expressed as sums of products between elements of the vector with elements of matrix rows 



\begin{equation}
\bf{A}\bf{x} =
\begin{bmatrix}
\sum_{j = 1}^m a_{1j} x_j\\
\vdots\\
\sum_{j = 1}^m a_{mj} x_j\\
\end{bmatrix}.
\end{equation}

#### Illustration of Vector Matrix Multiplication

* Let matrices $\bf{A}, \bf{B}$ and vector $\bf{x}$ 

\begin{equation}
\bf{A} = 
\begin{bmatrix}
2 & 0 \\
0 & 2
\end{bmatrix}, \quad
\bf{B} =
\begin{bmatrix}
-2 & 0\\
0 & -2
\end{bmatrix}, \quad
\bf{x} = 
\begin{bmatrix}
3\\
1
\end{bmatrix}.
\end{equation}

![](https://drive.google.com/uc?export=view&id=1XKBEF6v14HFyK6okt5bRYX7_G3DV6c9t)


#### Matrix Matrix Multiplication

* Product between matrices follows the same principle as matrice vector product;

* Consider $2 \times 2$ matrices $\bf{A}$ and $\bf{B}$;

\begin{equation}
\bf{A} =
\begin{bmatrix}
a_{11} & a_{12} \\
a_{21} & a_{22}
\end{bmatrix},
\quad
\bf{B} =
\begin{bmatrix}
b_{11} & b_{12} \\
b_{21} & b_{22}
\end{bmatrix}. 
\end{equation}

* The product $\bf{A}\bf{B}$ is

\begin{equation}
\bf{A}\bf{B} = 
\begin{bmatrix}
a_{11}b_{11} + a_{12}b_{21} & a_{11}b_{12} + a_{12}b_{22} \\
a_{21}b_{11} + a_{22}b_{21} & a_{21}b_{12} + a_{22}b_{22}
\end{bmatrix},
\end{equation}

* Matrix multiplication can be generalized:
  * Let $\bf{A} \in \rm I\!R^{m \times d}$ and $\bf{B} \in \rm I\!R^{d \times n}$;

  * Note that the number of columns in $\bf{A}$ **must be equal** to the number of rows in $\bf{B}$;

  * The dimension of the resulting matrix is $m \times n$ 


\begin{equation}
\bf{A} \times \bf{B} = 
\begin{bmatrix}
\sum_{j = 1} ^d a_{1j}b_{1j} & \ldots & \sum_{j = 1} ^d a_{1j}b_{nj} \\
\vdots & \ddots & \vdots \\
\sum_{j = 1} ^d a_{mj}b_{1j} & \ldots & \sum_{j = 1} ^d a_{mj}b_{nj}
\end{bmatrix}.
\end{equation}

#### Few Properties on operations between Matrices 



\begin{equation}
\bf{A}( \bf{B} + \bf{C} ) = \bf{A}\bf{B} + \bf{A}\bf{C}.
\end{equation}



* Multiplication is associative:



\begin{equation}
\bf{A} \left(\bf{B}\bf{C} \right) = \left(\bf{A}\bf{B}\right) \bf{C}. 
\end{equation}



* Multiplication is not commutative:



\begin{equation}
\bf{A}\bf{B}  \neq \bf{B}\bf{A}. 
\end{equation}


* Transpose of multiplication:



\begin{equation}
\left(\bf{A}\bf{B}\right)^T  = \bf{B}^T\bf{A}^T. 
\end{equation}

### Special Matrices

* Matrices are defined by their dimensions but also by the values inside the cells;

* There are some types of matrices with useful properties;
 

**Diagonal**

* Diagonal matrix are square with null values except in the diagonal

\\

\begin{equation}
\bf{D} =
\begin{bmatrix}
d_{11} & \ldots & 0 \\
\vdots & \ddots & \vdots \\
0 & \ddots & d_{dd}
\end{bmatrix}.
\end{equation}



**Identity**

* Identity matrices are diagonal matrices with $1$s in the diagonal;

* Identity matrice preserve input vectors both in direction and in length.

**Inverse**

* Let $\bf{A} \in \rm I\!R^m \times \rm I\!R^d$ be a matrix with $m$ rows and $d$ columns;

\\

* We define $\bf{A}^{-1} \in \rm I\!R^d \times \rm I\!R^m$ as the inverse of $\bf{A}$ that is:

\\

\begin{equation}
\bf{A}^{-1} \bf{A} = \bf{I}.
\end{equation}

\\

* Existence of $\bf{A}^{-1}$ must satisfy:

  * $\bf{A}$ must be square (number of rows = number of columns);

  * no linear dependence amongst columns of $\bf{A}$. 

**Symmetry**

* Symmetric matrix is any matrix that is equal to its own transpose:

\\

\begin{equation}
\bf{A} = \bf{A}^T.
\end{equation}

\\

* Symmetric matrices often arise when entries are generated by some functions of two arguments that does not depend on the order of  arguments such as Covariance or Distance between data.

**Orthonormality**

* Orthogonal matrix is square whose:

  * rows are mutually **orthonormal**; 

  * columns are mutually **orthonormal**.

\\

\begin{equation}
\bf{A}^T \bf{A} = \bf{A} \bf{A}^T = \bf{I}.
\end{equation}

* The equation above implies that:

\\

\begin{equation}
\bf{A}^{-1} = \bf{A}^T.
\end{equation}


### Matrix/Vector Spaces

#### **Determinant**

* Matrix $\bf{A}$ may transform single vectors $\bf{x}$ but it can also transform whole **vector space** when applied on every vector inside that space;

* For instance, let $\bf{A}$ be the $2 \times 2$ matrix 

\\

\begin{equation}
\bf{A} = 
\begin{bmatrix}
3 & 1 \\
1 & 2
\end{bmatrix}.
\end{equation}

\\

* Below we visualize original basis vectors $\bf{OC}$ and $\bf{OA}$ with their respective transformations $\bf{OF}$ and $\bf{OD}$;

\\

* It is easy to see that all input vectors laying inside the square $\bf{OABC}$ will end up inside the parallelogram $\bf{ODEF}$;
  

 ![](https://drive.google.com/uc?export=view&id=1O_nMth8P4Kg6fRB94yyAX3oKJOrG8Kiq)



* Matrix determinant $\bf{det}(\bf{A})$ is a scalar value

  * Whose value measures the ratio between the areas of $\bf{ODEF}$ and $\bf{OABC}$;

  * Whose sign is positive if the order between the basis vectors is unchanged and negative otherwise.

  * Whose value is equal to $0$ if at least one column vector of $\bf{A}$ is linearly dependent with the others (which leads to space contraction). 


\\

* For $2 \times 2$ matrices

\\

\begin{equation}
\bf{A} = 
\begin{bmatrix}
a & b \\
c & d
\end{bmatrix},
\end{equation}

\\

* determinant is given by $\bf{det}(A)$ $= ad - cb$.

\\

* For $3 \times 3$ matrices 

\begin{equation}
\bf{A} = 
\begin{bmatrix}
a & b & c \\
d & e & f \\
g & h & i
\end{bmatrix},
\end{equation}

\\


* the determinant is computed as follows:

\\

\begin{equation}
\bf{det(A)} = a .\bf{det}
\left(
\begin{bmatrix}
e & f \\
h & i
\end{bmatrix}
\right)
- b .\bf{det}
\left(
\begin{bmatrix}
d & f \\
g & i
\end{bmatrix}
\right)
+
c .\bf{det}
\left(
\begin{bmatrix}
d & e \\
g & h
\end{bmatrix}
\right).
\end{equation}

\\

* Same principle applies for higher dimensions. 

#### **Eigenvalues & Eigenvectors (Definitions)**




* When Matrix $\bf{A}$ is applied on  input vectors it tends to alter its length and/or direction; 


* Under some circumstances, certain vectors $\bf{v}$ get altered **only in their length** that is


\begin{equation}
\bf{A} \bf{v} = \lambda \bf{v}, \quad \lambda \neq 0, \bf{v} \neq \bf{0}.
\end{equation}


* This kind of vectors are known as **eigenvectors** and the coefficient of the length alteration is the corresponding **eigenvalue**.


* Note that if $\bf{v}$ is an eigenvector of $\bf{A}$, then:

  * So is any rescaled vector $s\bf{v}$ for any $s \neq 0$;

  * $s\bf{v}$ still has the same eigenvalue as $\bf{v}$.
  
![](https://drive.google.com/uc?export=view&id=1wg79WpAbYO6Z0uL2uPpLjMuhGxHoNgdW)

 * Eigenvalues are computed through the **characteristic equation** defined as

\begin{equation}
\begin{array}{11}
\bf{A} \bf{v}  & = & \lambda \bf{v} \\
\bf{A} \bf{v} - \lambda \bf{v} & = & 0,\\
\end{array}
\end{equation}

* resulting into polynomial in $\lambda$ where the roots are the eigenvalues of $\bf{A}$.

\begin{equation}
\bf{det} \left(\bf{A}  - \lambda \bf{I}\right) = 0.
\end{equation}

### Matrix Factorization

#### **Eigendecomposition**

* Factorization splits linear transformations into atomic steps like distinguishing between rotations and length alteration.

* Let $\bf{A}$ a **diagonalizable matrix** (square, invertible and verify other conditions);


* If $\bf{A}$ has $m$ linearly **independent** eigenvectors $\{ \bf{v}^{(1)},\ldots,\bf{v}^{(m)} \}$ with corresponding eigenvalues $\{ \lambda_1, \ldots, \lambda_m\}$ then  $\bf{A}$ can be **factorized** as;

\\

\begin{equation}
\bf{A}  = \bf{V} \bf{\Lambda} \bf{V}^{-1}.
\end{equation}

\\

* When $m$ eigenvectors are concatenated into matrix $\bf{V}$ and the associated eigenvalues in the diagonal matrix $\bf{\Lambda}$, $\bf{A}$ can be **factorized** as 

* Where $\bf{V}$ is concatenation of  $m$ eigenvectors ordered by descending absolute values of eigenvalues.

* If $\bf{A}$ is **symmetric** the matrix of eigenvectors $\bf{Q}$ is **orthogonal** and the factorization becomes

\\

\begin{equation}
\bf{A} = \bf{Q}\bf{\Lambda}\bf{Q}^T.
\end{equation}

#### **Singular Value Decomposition (SVD)**

* Singular Value Decomposition (SVD) provides another way to factorize a matrix;

* While eigendecomposition is not applicable to any matrix, SVD is;

* SVD decomposition has lot of applications like Image compression, Recommender Systems (Netflix, Spotify, Amazon,...); 






* Let $\bf{M}$ be a $m \times d$ matrix. The SVD decomposition of $\bf{M}$ is 

\begin{equation}
\bf{M} = \bf{U} \bf{\Sigma} \bf{V}^T,
\end{equation}


* where for a given input vector $\bf{x}$:

  *  $\bf{V}^T$ is $d \times d$ **orthogonal** matrix and performs rotation on $\bf{x}$ (we call $\bf{x}_V$); 

  *  $\bf{\Sigma}$ is $m \times d$ and performs streching of $\bf{x_V}$ then projects it into $m$ dimensions (we call $\bf{x}_{V\Sigma}$);

  *  $\bf{U}$ is $m \times m$ **orthogonal** matrix and performs last rotation on $\bf{x}_{V\Sigma}$. 


![](https://drive.google.com/uc?export=view&id=1tG4H8p5ALEJpbar63U__8oLGbTUYGcqv)


* $\bf{V}$ is constructed by the eigenvectors of $\bf{M}^T\bf{M}$;

* $\bf{U}$ is constructed by the eigenvectors of $\bf{M}\bf{M}^T$;

* $\bf{\Sigma}$ is diagonal matrix whose entries are called ***singular values*** and correspond to square root of the eigenvalues of $\bf{M}\bf{M}^T$ or $\bf{M}^T\bf{M}$;

* The number of **non-zero** singular values equals the rank of $\bf{M}$;

* If $\bf{\Sigma}$ is not square the rest of the diagonal are filled with zeros.

### Matrices in Python

In [ ]:
import numpy as np
#Creation of a 2 X 2 matrix
A = np.array([[2,1],[1,2]], dtype = np.float32)
print('Matrix A has the dimension ' + str(A.shape))
print('with the entries')
print(A)


#Product between two matrices
B = np.array([[3,4,1], [4,7,0]])
AB = A.dot(B)
print('Dimension of A.B = ' + str(AB.shape))
print('\nA.B = ')
print(AB)


#Transpose
ABt = AB.transpose()
print('Dimension of transposed AB = ' + str(ABt.shape))
print('\nTransposed AB = ')
print(ABt)


#Diagonal Matrix
D = np.diag([1,2,3,4,5,6])
print(D)

Matrix A has the dimension (2, 2)
with the entries
[[2. 1.]
 [1. 2.]]
Dimension of A.B = (2, 3)

A.B = 
[[10. 15.  2.]
 [11. 18.  1.]]
Dimension of transposed AB = (3, 2)

Transposed AB = 
[[10. 11.]
 [15. 18.]
 [ 2.  1.]]
[[1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]
 [0 0 0 0 0 6]]


In [ ]:
import numpy as np

#Determinant
A = np.array([[1, 2], [3, 4]])
detA = np.linalg.det(A)
print('Determinant of A = ' + str(detA))

#eigenvalues & eigenvectors
A = np.array([[2,1],[1,2]], dtype = np.float32)
lambdas, V = np.linalg.eig(A)
print('eigenvalues = ')
print(lambdas)
print('eigenvectors = ')
print(V)

#SVD decomposition
U, Sigma, Vt = np.linalg.svd(A)




Determinant of A = -2.0000000000000004
eigenvalues = 
[3. 1.]
eigenvectors = 
[[ 0.70710677 -0.70710677]
 [ 0.70710677  0.70710677]]


#2. Optimization/Calculus Prerequisites 

## Introduction into Optimization

* Mathematical optimization consists in maximizing or minimizing some function $f$ known as **objective function**.

    * If for example $f$ measures business profit, optimization of $f$ seeks $x$ for which $f$ is the highest.
    
    * In case $f$ measures the error of mathematical model with respect to some parameter value $x$, optimization of $f$ looks for $x$ for which $f$ is the minimum.

* Optimal values are known as **critical points** 

![](https://drive.google.com/uc?export=view&id=1KKBWOHSQk2E9qSpgG0X7TWi_KrSimE0f)

* Objective function $f$ might have many critical points;

* Critical points in such situations are said to be **local**;

* The best optimum is called **global**.

![](https://drive.google.com/uc?export=view&id=1vZ3xvIoQtINiTmlSrbnY1W3gj0AsiH4C)

* Oftentimes $f$ depends on several variables. Below is an example of an objective function with two variables 

$$
f(x_1,x_2) = x_1^2 + x_2^2
$$

* Minimizing  $f(x_1,x_2)$ means finding the values of $x_1,x_2$ that bring $f$  represented by the blue envelop hit the ground.

![](https://drive.google.com/uc?export=view&id=1dC2BI7ZQ7I0ca9Ov8905nFcd_0deMfwD)

## First Order Optimization

* Unconstrained Optimization refers to the problems where no restriction is made over values that $x$ can take;


* Several methods exist to solve optimization problems.  We focus on Gradient Based approaches;

### Derivation (Intuition)

* Consider the case where $x$ is scalar, critical points of $f$ can be found through mathematical tool called **derivation**.

* Informally, derivative of $f$ at $x$ is the **inclination** known as **slope** of the line that touches $f(x)$. 

![](https://drive.google.com/uc?export=view&id=1QaraySjBXyfG11XllHl0KQ4FO_BTRwly)

* The sign of the slope (positive, negative or nul) indicates from a given $x$ the direction where $f(x)$ is heading (up, down or no where):

* Arrows below $f$ whose **inclinations** correspond to derivatives of $f$ at different $x$ (the length of the arrows has no particular meaning);
    
* Critical points (optimum) match with null derivatives;

* Derivatives are defined as functions in $x$ which means identifying $x$ for which the derivative function equates zero take us to critical points;

![](https://drive.google.com/uc?export=view&id=1arJWq2pSyLxkm-daUxZeEA2tncbIJIs3)



### Derivation  (Formal Definition)

* Let $f(x)$ be real function differentiable at every $x$ (*** differentiable at every $x$ means smooth curve with no abrupt changes***). 

* We define $\frac{d}{dx}$ as derivative operator applied to  $f$ with respect to $x$ such that

\begin{equation}
\frac{df(x)}{dx} =  \underset{h \rightarrow 0}{\mbox{lim}} \frac{f(x + h) - f(x)}{(x + h) - x} = \underset{h \rightarrow 0}{\mbox{lim}} \frac{f(x + h) - f(x)}{h}.
\end{equation}

* The above equation produces  new function $f^{'}(x)$ that indicates for every $x$ the rate of change of $f(x)$ surrounding an **infinitesimally small** region near $x$.

* When $h$ is very small, function $f$ is well-approximated with straight line and derivative is its slope.  

### Rules of Derivation

* Let $f(x),g(x)$ be two differentiable functions and $a,b$ two reals. 

\\

  1. **Constant Rule**:
  \begin{equation}
  \frac{d}{dx}(a) = 0.
  \end{equation}

\\

  2. **Power Rule**:
  \begin{equation}
   \frac{d}{dx}(x^n) = n x^{n-1}.
  \end{equation}

\\

  3. **Linearity Rules**:

  \begin{equation}
  \left [a f(x)\right]^{'} = a f^{'}(x). \\
  \left[ f(x) \pm  g(x) \right]^{'} = f^{'}(x) \pm g^{'}(x).
  \end{equation}
    
\\

  4. **Product Rule**:  


  \begin{equation}
  \left[f(x) \times g(x)\right]^{'} = f^{'}(x) \times g(x) + f(x) \times g^{'}(x). 
  \end{equation}
   
\\

  5. **Quotient Rule**:  

  \begin{equation}
  \left[\frac{f(x)}{g(x)}\right]^{'} = \frac{f^{'}(x) \times g(x) -  f(x) \times g^{'}(x))}{g^{2}(x)}.
  \end{equation}
    
\\

  6. **Common Functions**:
  \begin{equation}
  \left[ \log(x) \right]^{'} = \frac{1}{x},\quad x > 0.\\
  \left[ \exp(x) \right]^{'} = \exp(x).\\
  \left[ \sin(x) \right]^{'} =  \cos(x).\\
  \left[ \cos(x)\right]^{'} = - \sin(x).\\
  \left[ tanh(x)\right]^{'} = 1 - tanh(x)^2
  \end{equation}
  
  
\\

  7. **Chain Rule**:
  \begin{equation}
  \frac{d}{dx} \left( f(g(x))  \right) = f^{'}\left( g(x)\right) g^{'}(x).
  \end{equation}

### Gradient

* Gradient is the extention of derivative when $\bf{x}$ is a vector.

* Let $y = f(x_1,\ldots,x_k)$ be a function from ${\rm I\!R}^k$ to ${\rm I\!R}$.

* We define $\frac{\partial y}{\partial x_j}$ as the **partial derivative** of $y$ w.r.t $x_j$ which corresponds to $\frac{d}{dx_j}(y)$ where all  $x_i,i \neq j$ are  considered constant.

* We define $\nabla_{\bf{x}}$ , the gradient operator with respect to $\bf{x} = [x_1,\ldots,x_k]^T$ applied to $y$ as vector of all partial derivatives

\begin{equation}
\nabla_{\bf{x}} y =  
\begin{bmatrix}
\frac{\partial y}{\partial x_1} \\
\vdots\\
\frac{\partial y}{\partial x_k} 
\end{bmatrix}.
\end{equation}

* Each element $\frac{\partial y}{\partial x_j}$ indicates the effect of $x_j$ on $y$ when $x_j$ increases by an  infinitesimally small quantity $h$. 

# Exercice 1

### Problem

* let $f(x_1,x_2) = 2x_1^2 + 4x_2^2 - 10$ be an objective function to be minimized;


* Knowing that $f(x)$ is **convex**, use the gradient to find the minimum of $f$ ?

### Solution

* Critical point of $f(x_1,x_2)$ is determined by values of $x_1,x_2$ for which

\\


$$
\nabla f = 
\begin{bmatrix}
0 \\
0
\end{bmatrix}, \iff
\left\{
\begin{array}{ll}
4x_1 = 0,\\
8x_2 = 0 ,
\end{array}
\right.
\iff
\left\{
\begin{array}{ll}
x_1 = 0,\\
x_2 = 0 .
\end{array}
\right.
$$

* Equating gradient to the null vector and finding $\bf{x}$ that satisfies that equation is refered as the **analytic** approach.


* This approach becomes impractible when it comes to functions with millions of variables;


* An alternative is to use **iterative** approaches like the gradient descent algorithm.

# Gradient Descent 

* Gradient Descent is a simple algorithm used to optimize multivariable functions ($f(\bf{x})$ where $\bf{x} = [x_1,\ldots,x_k]^T$). 

* Consider minimization problem, gradient descent proceeds as follows:

![](https://drive.google.com/uc?export=view&id=1CODDYsJPk41eYGWNRKJBWiEvVGAWoraN)



* initialize random solution $\bf{x}^*$ (for example it may randomly start at $x^* = 6$);




* update iteratively  $\bf{x}^*$ in such way $f$ decreases  ($x^* = 4, 2, 0$ after first, second and third updates);




* end the process after some criterion is met (number of iterations, value of $f\ldots$).


* Gradient Descent requires two mecanisms 
    1.  $\lambda > 0$ refered as **convergence rate** regulating the length of step by which the solution moves.
    2. Stopping Condition:
    
      *  Oftentimes number of iterations $N$;
      
      * Another way is to set threshold $\delta \in {\rm I\!R}$ such that $f(\bf{x}^*) <= \delta$.
      
      * The two stopping criterions can be combined.
    
* Update operation is peformed on each element $x_j^{*[i]}$ as follows

\begin{equation}
x_{j}^{*[i]} \leftarrow x_{j}^{*[i-1]} - \lambda \frac{\partial f}{\partial x_{j}^{*[i-1]}}, 
\end{equation}

where $x_{j}^{*[i]}$ is the value of $x_{j}^{*}$ at $i^{th}$ iteration.

* Gradient descent algorithm can be formally summarized as:
       
 * **Initialize Solution**: 
     \begin{equation}
     \bf{x}^{*[0]} \leftarrow \mbox{Random()};
     \end{equation}
     
 * **For** $i = 1,\ldots,N$:
     
      * **Compute Gradient** :
     
        \begin{equation}
      \nabla_{\bf{x}^{[i]}} f =  
      \begin{bmatrix}
      \frac{\partial f}{\partial x_1^{[i]}}\\
      \vdots\\
      \frac{\partial f}{\partial x_k^{[i]}}
      \end{bmatrix};
      \end{equation}   
      
      * **Update Solution**:        
         \begin{equation}
         \bf{x}^{*[i]} \leftarrow  \bf{x}^{*[i-1]} - \lambda \nabla_{\bf{x}^{[i]}} f;
        \end{equation}  